name: build-and-check

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs-version: ['17', '16.13', '14.18', '12.22']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: Install dependencies
        run: npm i

      - name: Check code
        run: npm run check:all

      - name: AWS Lambda bundle
        run: npm run bundle:aws

      - name: Local server bundle
        run: npm run bundle:server
